# Generated by Django 6.1 on 2026-09-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
    ]
