# Generated by Django 6.1 on 2026-09-04 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_submission_repo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
